// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Z4_Al_5VS9dzBycZOgr999L0w0piwn0',
    appId: '1:76373273497:android:4721a394c47ca917034108',
    messagingSenderId: '76373273497',
    projectId: 'ecommerce-a196b',
    storageBucket: 'ecommerce-a196b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMaVdlJK5Ami8orS_Wq31l_UtFgLYwjj4',
    appId: '1:76373273497:ios:934acbf9514f7bcb034108',
    messagingSenderId: '76373273497',
    projectId: 'ecommerce-a196b',
    storageBucket: 'ecommerce-a196b.appspot.com',
    androidClientId: '76373273497-k650ft43hf62q2frotno3u050vpnd1qd.apps.googleusercontent.com',
    iosClientId: '76373273497-ah3iq9p6794ilvh3uudsk503emon1es7.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceBackend',
  );
}
